# Site
title:              Ng Wei Shyang
bio:                'A.K.A Tony'
description:        "Just another Homo sapiens who are interested in life and death"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       "UA-120218320-1"
twitter:            TonyNgWS97
facebook:           gaara4896
instagram:          nws1997
github:             gaara4896
linkedin:           in/tony-ng-wei-shyang-357856134

# personal
location:           Selangor, MY
phone:              +60 17-215 8366
email:              tonyngws97@gmail.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old elements.html]
